const TokenType = Object.freeze({
  LEFT_PAREN: "LEFT_PAREN",
  RIGHT_PAREN: "RIGHT_PAREN",
  LEFT_BRACE: "LEFT_BRACE",
  RIGHT_BRACE: "RIGHT_BRACE",
  LEFT_BRACKET: "LEFT_BRACKET",
  RIGHT_BRACKET: "RIGHT_BRACKET",
  COMMA: "COMMA",
  DOT: "DOT",
  MINUS: "MINUS",
  PLUS: "PLUS",
  SEMICOLON: "SEMICOLON",
  SLASH: "SLASH",
  STAR: "STAR",
  PERCENT: "PERCENT",
  BANG: "BANG",
  BANG_EQUAL: "BANG_EQUAL",
  EQUAL: "EQUAL",
  EQUAL_EQUAL: "EQUAL_EQUAL",
  GREATER: "GREATER",
  GREATER_EQUAL: "GREATER_EQUAL",
  LESS: "LESS",
  LESS_EQUAL: "LESS_EQUAL",
  IDENTIFIER: "IDENTIFIER",
  STRING: "STRING",
  NUMBER: "NUMBER",
  AND: "AND",
  CLASS: "CLASS",
  ELSE: "ELSE",
  FALSE: "FALSE",
  FROM: "FROM",
  FUNC: "FUNC",
  IF: "IF",
  IMPORT: "IMPORT",
  LET: "LET",
  LOOP: "LOOP",
  NULL: "NULL",
  OR: "OR",
  RETURN: "RETURN",
  SELF: "SELF",
  STEP: "STEP",
  TO: "TO",
  TRUE: "TRUE",
  NEWLINE: "NEWLINE",
  EOF: "EOF",
});

const KEYWORDS = Object.freeze({
  and: TokenType.AND,
  class: TokenType.CLASS,
  else: TokenType.ELSE,
  false: TokenType.FALSE,
  from: TokenType.FROM,
  func: TokenType.FUNC,
  if: TokenType.IF,
  import: TokenType.IMPORT,
  let: TokenType.LET,
  loop: TokenType.LOOP,
  null: TokenType.NULL,
  or: TokenType.OR,
  return: TokenType.RETURN,
  self: TokenType.SELF,
  step: TokenType.STEP,
  to: TokenType.TO,
  true: TokenType.TRUE,
});

function createToken(type, lexeme, literal, line, column, filePath = null) {
  return {
    type,
    lexeme,
    literal,
    line,
    column,
    filePath,
  };
}

module.exports = {
  KEYWORDS,
  TokenType,
  createToken,
};
